api:
  auth_token: {{AUTH_TOKEN}}

runner:
  name: {{RUNNER_NAME}}
  command_prefix : ["sudo", "-niHu", "{{USERNAME}}", "--"]
  working_directory: /tmp/%s
  cleanup_working_directory: true

logging:
  file: /Library/Logs/com.circleci.runner.log
